#!/bin/bash
# The name of the job, can be anything, simply used when displaying the list of running jobs
#$ -N simtest
# Combining output/error messages into one file
#$ -j y
# Set memory request:
#$ -l vf=4G
# Set walltime request:
#$ -l h_rt=00:30:00
# One needs to tell the queue system to use the current directory as the working directory
# Or else the script may fail as it will execute in your top level home directory /home/username
#$ -cwd
# then you tell it retain all environment variables (as the default is to scrub your environment)
#$ -V
# Now comes the command to be executed
# job_id=$1
module load gcc/6.2.0
g++ -std = c++11 new_S1_sim.cpp - lpthread - o new_S1_sim
./new_S1_sim qwerty_hashlist.txt layout_12.txt /home/ifsdata/xd/jhluo/test/output_12.txt
exit 0
